# Generated by Django 4.2.7 on 2023-11-11 01:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VMs',
            fields=[
                ('idvm', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VMPlacementSpec',
            fields=[
                ('idplacement', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datastore', models.CharField(max_length=255)),
                ('folder', models.CharField(max_length=255)),
                ('vm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='VMS.vms')),
            ],
        ),
    ]
