# Generated by Django 4.2.7 on 2023-11-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vms',
            name='guest_OS',
            field=models.CharField(choices=[('DOS', 'MS-DOS'), ('WIN_31', 'Windows 3.1'), ('WIN_95', 'Windows 95'), ('WIN_98', 'Windows 98'), ('WIN_ME', 'Windows Millennium Edition'), ('WIN_NT', 'Windows NT 4'), ('WIN_2000_PRO', 'Windows 2000 Professional'), ('WIN_2000_SERV', 'Windows 2000 Server'), ('WIN_2000_ADV_SERV', 'Windows 2000 Advanced Server'), ('WIN_XP_HOME', 'Windows XP Home Edition'), ('WIN_XP_PRO', 'Windows XP Professional'), ('WIN_XP_PRO_64', 'Windows XP Professional Edition (64 bit)'), ('WIN_NET_WEB', 'Windows Server 2003, Web Edition'), ('WIN_NET_STANDARD', 'Windows Server 2003, Standard Edition'), ('WIN_NET_ENTERPRISE', 'Windows Server 2003, Enterprise Edition'), ('WIN_NET_DATACENTER', 'Windows Server 2003, Datacenter Edition'), ('WIN_NET_BUSINESS', 'Windows Small Business Server 2003'), ('WIN_NET_STANDARD_64', 'Windows Server 2003, Standard Edition (64 bit)'), ('WIN_NET_ENTERPRISE_64', 'Windows Server 2003, Enterprise Edition (64 bit)'), ('WIN_LONGHORN', 'Windows Longhorn'), ('WIN_LONGHORN_64', 'Windows Longhorn (64 bit)'), ('WIN_NET_DATACENTER_64', 'Windows Server 2003, Datacenter Edition (64 bit)'), ('WIN_VISTA', 'Windows Vista')], default='DOS', max_length=255),
        ),
    ]
