# Generated by Django 4.2.7 on 2023-11-18 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0003_alter_vms_guest_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vms',
            name='guest_OS',
            field=models.CharField(max_length=255),
        ),
    ]
