# Generated by Django 4.2.7 on 2023-11-19 17:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0004_alter_vms_guest_os'),
    ]

    operations = [
        migrations.CreateModel(
            name='placement',
            fields=[
                ('idplacement', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datastore', models.CharField(max_length=255)),
                ('folder', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='spec',
            fields=[
                ('idspec', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_OS', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='vms',
            name='guest_OS',
        ),
        migrations.RemoveField(
            model_name='vms',
            name='name',
        ),
        migrations.DeleteModel(
            name='VMPlacementSpec',
        ),
        migrations.AddField(
            model_name='vms',
            name='spec',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VMS.spec'),
        ),
    ]
