# Generated by Django 4.2.7 on 2023-11-21 05:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0006_spec_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMCreateSpec',
            fields=[
                ('idspec', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cluster', models.CharField(max_length=255)),
                ('guest_OS', models.CharField(choices=[('DOS', 'MS-DOS'), ('WIN_31', 'Windows 3.1')], default='DOS', max_length=255)),
                ('datastore', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('resource_pool', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='vms',
            name='spec',
        ),
        migrations.RenameModel(
            old_name='placement',
            new_name='VMPlacementSpec',
        ),
        migrations.DeleteModel(
            name='spec',
        ),
        migrations.DeleteModel(
            name='VMs',
        ),
        migrations.AddField(
            model_name='vmcreatespec',
            name='placement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VMS.vmplacementspec'),
        ),
    ]
