# Generated by Django 4.2.7 on 2023-11-21 09:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0008_alter_vmcreatespec_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMs',
            fields=[
                ('idvm', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='VMS.vmcreatespec')),
            ],
        ),
    ]
