# Generated by Django 4.2.7 on 2023-11-21 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0009_vms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmcreatespec',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='vmcreatespec',
            name='datastore',
        ),
        migrations.RemoveField(
            model_name='vmcreatespec',
            name='host',
        ),
        migrations.RemoveField(
            model_name='vmcreatespec',
            name='resource_pool',
        ),
    ]
