# Generated by Django 4.2.7 on 2023-11-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0010_remove_vmcreatespec_cluster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmcreatespec',
            name='guest_OS',
            field=models.CharField(choices=[('DOS', 'MS-DOS'), ('WIN_31', 'Windows 3.1')], default='MS-DOS', max_length=255),
        ),
    ]
